/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gestio.Atraccions;

import Classes.Atraccio;
import javax.swing.JOptionPane;
import Biblioteques.Auxiliar;
import Biblioteques.IO;
import static Main.config.carregarConf;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Manu
 */
public class CreaAtraccioForm extends javax.swing.JFrame {

    /**
     * Creates new form CreaAtraccioForm
     */
    public CreaAtraccioForm() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Crear Atraccio");
        try{
            getContentPane().setBackground(Color.decode(Main.config.carregarConf()[0]));
        }catch (Exception e){
            IO.imprimirTI("Error al asignar color: " + e);
        }
        try{
            Component[] components1=getContentPane().getComponents();
            Main.config.setUIFont(new Font(carregarConf()[1], Integer.valueOf(carregarConf()[2]), Integer.valueOf(carregarConf()[3])), components1);            
        }catch(Exception e){
            IO.imprimirTI("Error al carregar la font: " + e);
        }
        data.setDateFormatString("dd/MM/yyyy");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomAtraccio = new javax.swing.JTextField();
        tipusAtraccio = new javax.swing.JTextField();
        alturaMin = new javax.swing.JTextField();
        accessibilitat = new javax.swing.JTextField();
        Express = new javax.swing.JTextField();
        CrearButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        data = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar atracció");

        nomAtraccio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomAtraccioActionPerformed(evt);
            }
        });

        tipusAtraccio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipusAtraccioActionPerformed(evt);
            }
        });

        alturaMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturaMinActionPerformed(evt);
            }
        });

        accessibilitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accessibilitatActionPerformed(evt);
            }
        });

        Express.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpressActionPerformed(evt);
            }
        });

        CrearButton.setText("Crear");
        CrearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearButtonActionPerformed(evt);
            }
        });

        ClearButton.setText("Esborrar");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancelar");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Nom: ");

        jLabel4.setText("Tipus:");

        jLabel5.setText("Data innauguració: ");

        jLabel6.setText("Altura mínima:");

        jLabel7.setText("Accessibilitat");

        jLabel8.setText("Access  Express");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Express, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nomAtraccio, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                        .addComponent(tipusAtraccio)
                        .addComponent(accessibilitat)
                        .addComponent(alturaMin))
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(291, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CrearButton)
                        .addGap(18, 18, 18)
                        .addComponent(ClearButton)
                        .addGap(18, 18, 18)
                        .addComponent(CancelButton)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(279, 279, 279))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nomAtraccio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tipusAtraccio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5))
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(alturaMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(accessibilitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Express, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrearButton)
                    .addComponent(ClearButton)
                    .addComponent(CancelButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void CrearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearButtonActionPerformed
        if (nomAtraccio.getText().isEmpty() || tipusAtraccio.getText().isEmpty() || data.toString().isEmpty() || alturaMin.getText().isEmpty() || accessibilitat.getText().isEmpty() || Express.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Error: Hi ha algun camp per a omplir");
                    IO.imprimirTI("Se ha intentat registrar una  en algun camp buit");
                }else {
            try{
                DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
                nomAtraccio.getText();   
                tipusAtraccio.getText();
                //dataInnauguracio.getText();
                alturaMin.getText();
                accessibilitat.getText();
                Express.getText();
                
                Date time = data.getCalendar().getTime();  
                String data2 = df.format(time);
                IO.imprimirTI("" + data2);
                
                Atraccio.arrayAtraccio.add(new Atraccio(nomAtraccio.getText(),tipusAtraccio.getText(),data2,alturaMin.getText(),accessibilitat.getText(),Express.getText()));
                JOptionPane.showMessageDialog(this, "Atraccio registrada correctament");
                Auxiliar.log("Atraccio registrada: " + Atraccio.arrayAtraccio.get(Atraccio.arrayAtraccio.size()-1).getNom() + " | " + Atraccio.arrayAtraccio.get(Atraccio.arrayAtraccio.size()-1).getTipusAtraccio() + " | " + Atraccio.arrayAtraccio.get(Atraccio.arrayAtraccio.size()-1).getDataInauguracio() + " | " + Atraccio.arrayAtraccio.get(Atraccio.arrayAtraccio.size()-1).getAlturaMin() + " | " + Atraccio.arrayAtraccio.get(Atraccio.arrayAtraccio.size()-1).getAccessibilitat() + " | " + Atraccio.arrayAtraccio.get(Atraccio.arrayAtraccio.size()-1).getAccesExpress() + " | " + Atraccio.arrayAtraccio.get(Atraccio.arrayAtraccio.size()-1).getDataCreacioRegistre());
                this.setVisible(false);
                MenuAtraccioForm menuA = new MenuAtraccioForm();
                menuA.setVisible(true);
            }catch (Exception e){
                //log error
                IO.imprimirTI("Error al registrar atraccio: " + e);
                Auxiliar.logError("Error al registrar una atraccio: " + e);
                JOptionPane.showMessageDialog(this, "Error: Hi ha algun camp incorrecte");
            }
        }
        
    }//GEN-LAST:event_CrearButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        nomAtraccio.setText("");
        tipusAtraccio.setText("");
        try{
          data.getCalendar().setTime(new SimpleDateFormat("dd/MM/yyyy").parse(""));  
        }catch(Exception e){
            IO.imprimirTI("petadeta.jar: " + e);
        }
        alturaMin.setText("");
        accessibilitat.setText("");
        Express.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void nomAtraccioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomAtraccioActionPerformed
        
        
    }//GEN-LAST:event_nomAtraccioActionPerformed

    private void tipusAtraccioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipusAtraccioActionPerformed
     
    }//GEN-LAST:event_tipusAtraccioActionPerformed

    private void alturaMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturaMinActionPerformed
        
    }//GEN-LAST:event_alturaMinActionPerformed

    private void accessibilitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessibilitatActionPerformed
       
    }//GEN-LAST:event_accessibilitatActionPerformed

    private void ExpressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpressActionPerformed
        
    }//GEN-LAST:event_ExpressActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.setVisible(false);
        MenuAtraccioForm menuAtraccio = new MenuAtraccioForm();
        menuAtraccio.setVisible(true);
    }//GEN-LAST:event_CancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreaAtraccioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreaAtraccioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreaAtraccioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreaAtraccioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreaAtraccioForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton CrearButton;
    private javax.swing.JTextField Express;
    private javax.swing.JTextField accessibilitat;
    private javax.swing.JTextField alturaMin;
    private com.toedter.calendar.JDateChooser data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nomAtraccio;
    private javax.swing.JTextField tipusAtraccio;
    // End of variables declaration//GEN-END:variables
}
